import Head from 'next/head'

const about = (props) => {
    return (
        <div>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>About page</h1>
        </div>
    );
}

export default about;